apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- service.yaml
- manager.yaml

images:
- name: controller
  newName: container-registry.oracle.com/middleware/coherence-operator
  newTag: 3.5.7
