apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- webhook-secret.yaml
- service.yaml
- manager.yaml

images:
- name: controller
  newName: container-registry.oracle.com/middleware/coherence-operator
  newTag: 3.5.4
