apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- webhook-secret.yaml
- manager.yaml
- service.yaml

images:
- name: controller
  newName: ghcr.io/oracle/coherence-operator
  newTag: 3.4.3
