apiVersion: v1
kind: Service
metadata:
  name: webhook
  namespace: default
  labels:
    control-plane: coherence
    app.kubernetes.io/name: coherence-operator
    app.kubernetes.io/instance: coherence-operator-webhook
    app.kubernetes.io/version: "3.4.3"
    app.kubernetes.io/component: webhook
    app.kubernetes.io/part-of: coherence-operator
spec:
  ports:
    - name: https-webhook
      port: 443
      targetPort: webhook-server
  selector:
    app.kubernetes.io/name: coherence-operator
    app.kubernetes.io/instance: coherence-operator-manager
    app.kubernetes.io/version: "3.4.3"
    app.kubernetes.io/component: manager
---
apiVersion: v1
kind: Service
metadata:
  name: rest
  namespace: default
  labels:
    control-plane: coherence
    app.kubernetes.io/name: coherence-operator
    app.kubernetes.io/instance: coherence-operator-rest
    app.kubernetes.io/version: "3.4.3"
    app.kubernetes.io/component: rest
    app.kubernetes.io/part-of: coherence-operator
spec:
  ports:
    - name: http-rest
      port: 8000
      targetPort: operator
  selector:
    app.kubernetes.io/name: coherence-operator
    app.kubernetes.io/instance: coherence-operator-manager
    app.kubernetes.io/version: "3.4.3"
    app.kubernetes.io/component: manager
