#  Copyright (c) 2021, Oracle and/or its affiliates.
#  Licensed under the Universal Permissive License v 1.0 as shown at
#  http://oss.oracle.com/licenses/upl.
#
apiVersion: v1
kind: Secret
metadata:
  name: coherence-webhook-server-cert
  namespace: coherence
  labels:
    control-plane: coherence
