apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

labels:
  - pairs:
      control-plane: coherence
      app.kubernetes.io/name: coherence-operator
      app.kubernetes.io/version: "3.5.4"
      app.kubernetes.io/part-of: coherence-operator
