#
# Copyright (c) 2020, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at
# http://oss.oracle.com/licenses/upl.
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-grafana-datasource
  namespace: coherence-example
data:
  prometheus.yaml: |-
    {
        "apiVersion": 1,
        "datasources": [
            {
                "access":"proxy",
                "editable": true,
                "name": "Prometheus",
                "isDefault": true,
                "orgId": 1,
                "type": "prometheus",
                "url": "http://prometheus-operated:9090/",
                "version": 1
            }
        ]
    }
