{{/* Copyright 2019, Oracle Corporation and/or its affiliates.  All rights reserved. */}}
{{/* Licensed under the Universal Permissive License v 1.0 as shown at               */}}
{{/* http://oss.oracle.com/licenses/upl.                                             */}}

{{- if .Values.logCaptureEnabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "coherence-operator.fullname" . }}-efk-config
  labels:
{{- include "coherence-operator.release_labels" . | indent 4 }}
    component: coherence-operator-config
data:
  fluentd-coherence.conf: |
    # Ignore fluentd messages
    <match fluent.**>
      @type null
    </match>

    # Coherence Kubernetes Operator
    <source>
      @type tail
      path /logs/*.log
      pos_file /tmp/cohrence-operator.log.pos
      read_from_head true
      multiline_flush_interval 10s
      tag coherence-operator
      multiline_flush_interval 20s
      <parse>
       @type multiline
       format_firstline /^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}.\d{3} Coherence Kubernetes Operator/
       format1 /^(?<time>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}.\d{3}) Coherence Kubernetes Operator <(?<level>[^\s]+)> \((?<class>[a-z][$a-zA-z\.0-9]+) (?<method>[A-Za-z][A-Za-z0-9_]+)\):[\S\s](?<log>.*)/
      </parse>
    </source>

    <filter coherence-operator>
      @type record_transformer
      <record>
        pod-uid "#{ENV['OPERATOR_POD_ID']}"
      </record>
    </filter>

    <match coherence-operator>
      @type elasticsearch
      host "#{ENV['ELASTICSEARCH_HOST']}"
      port "#{ENV['ELASTICSEARCH_PORT']}"
  {{- if .Values.elasticsearchEndpoint }}
    {{- if .Values.elasticsearchEndpoint.user }}
      user "#{ENV['ELASTICSEARCH_USER']}"
    {{- end }}
    {{- if .Values.elasticsearchEndpoint.password }}
      password "#{ENV['ELASTICSEARCH_PASSWORD']}"
    {{- end }}
  {{- end }}
      logstash_format true
      logstash_prefix coherence-operator
    </match>
{{- end}}
