# Copyright 2019 Oracle Corporation and/or its affiliates.  All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at
# http://oss.oracle.com/licenses/upl.

# A values file used to generate the Operator SDK testing manifest when running
# end-to-end tests on k8s clusters such as OCI.

imagePullSecrets:
  - coherence-k8s-operator-development-secret
  - ocr-k8s-operator-development-secret

coherenceOperator:
  imagePullPolicy: Always
