apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/coherence.oracle.com_coherence.yaml
- bases/coherence.oracle.com_coherencejob.yaml
# +kubebuilder:scaffold:crdkustomizeresource

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml

patches:
- path: patches/coherence.oracle.com_coherence_crd_patch.json
  target:
    group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: coherence.coherence.oracle.com
    version: v1
- path: patches/coherence.oracle.com_coherence_crd_patch.json
  target:
    group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: coherencejob.coherence.oracle.com
    version: v1

labels:
- pairs:
    app.kubernetes.io/component: crd
    app.kubernetes.io/instance: coherence-operator-crd
    app.kubernetes.io/name: coherence-operator
    app.kubernetes.io/part-of: coherence-operator

commonLabels:
  app.kubernetes.io/version: 3.5.8
