apiVersion: batch/v1
kind: Job
metadata:
  name: test-web-hook
  labels:
    coherenceNetTest: webhook-client
spec:
  template:
    metadata:
      labels:
        coherenceNetTest: webhook-client
    spec:
      containers:
      - name: net-test
        image: ghcr.io/oracle/coherence-operator:3.4.3
        env:
          - name: OPERATOR_HOST
            value: net-test-operator-server.coherence.svc
        command:
          - /files/runner
        args:
          - net-test
          - hook
      restartPolicy: Never
  backoffLimit: 4
